use BT2QLDA

create table NHANVIEN
(
	MANV VARCHAR(5) PRIMARY KEY NOT NULL ,HONV NVARCHAR(20) NOT NULL, TENLOT NVARCHAR(20) NOT NULL,
	TENNV NVARCHAR(10) NOT NULL ,NGAYSINH DATE NOT NULL,DIACHI NVARCHAR(100) NOT NULL ,
	PHAI VARCHAR(5) NOT NULL ,LUONG DECIMAL(10,2)NOT NULL ,MAPB VARCHAR(5) NOT NULL
)
create table PHONGBAN 
(
	MAPB VARCHAR(5) PRIMARY KEY NOT NULL, TENPB NVARCHAR(50) NOT NULL, 
	TRUONGPHONG VARCHAR(5), NG_NHANCHUC DATE 
)
create table DEAN
(
	MADA VARCHAR(5) PRIMARY KEY NOT NULL,TENDA NVARCHAR(50) NOT NULL,
	DDIEM_DA NVARCHAR(100) NOT NULL,MAPB VARCHAR(5)  foreign key references PHONGBAN(MAPB)
)
DROP TABLE DEAN
